import { tool as createTool } from 'ai';
import { z } from 'zod';

export const FactTool = createTool({
  description: 'Generate Facts about Pi ',
  parameters: z.object({
    // No parameters needed for basic fact generation
  }),
  execute: async function ({}) {
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Collection of Pi facts
    const piFacts = [
      "Pi (π) is approximately equal to 3.14159265358979323846...",
      "Pi is an irrational number, meaning it cannot be expressed as a fraction.",
      "March 14 (3/14) is celebrated as Pi Day worldwide.",
      "The symbol for pi (π) was first used in 1706 by mathematician William Jones.",
      "Pi has been calculated to over 100 trillion digits.",
      "The record for memorizing digits of Pi is held by Rajveer Meena, who recited 70,000 digits in 2015.",
      "In the ancient world, the Babylonians estimated Pi to be 3.125.",
      "Albert Einstein was born on Pi Day (March 14, 1879).",
      "If you write 3.14 on a paper and hold it up to a mirror, it spells 'PIE'.",
      "The first 144 digits of Pi sum to 666.",
      "NASA scientists use Pi to calculate interplanetary trajectories for spacecraft.",
      "Some mathematicians celebrate Pi Approximation Day on July 22 (22/7).",
      "Pi appears in the Heisenberg Uncertainty Principle and other physics equations.",
      "Pi is used in calculating the area of a circle: A = πr².",
      "The circumference of a circle is calculated as C = 2πr.",
      "Pi is used in Fourier transforms and signal processing.",
      "The digits of Pi have no repeating pattern.",
      "Pi is used in probability theory and statistics.",
      "Pi is essential in the field of trigonometry.",
      "The Great Pyramid of Giza is thought to encode Pi in its dimensions.",
      "Pi is used in the calculation of wave functions in quantum mechanics.",
      "Pi is used in the design of gears and mechanical systems.",
      "Pi is used in the calculation of electromagnetic waves.",
      "Pi is used in the study of fractals.",
      "Pi is used in the calculation of the volume of spheres.",
      "Pi is used in the calculation of the surface area of spheres.",
      "Pi is used in the calculation of the volume of cylinders.",
      "Pi is used in the calculation of the surface area of cylinders.",
      "Pi is used in the calculation of the volume of cones.",
      "Pi is used in the calculation of the surface area of cones.",
      "Pi is used in the calculation of the volume of ellipsoids.",
      "Pi is used in the calculation of the surface area of ellipsoids.",
      "Pi is used in the calculation of the volume of tori.",
      "Pi is used in the calculation of the surface area of tori.",
      "Pi is used in the calculation of the volume of paraboloids.",
      "Pi is used in the calculation of the surface area of paraboloids.",
      "Pi is used in the calculation of the volume of hyperboloids.",
      "Pi is used in the calculation of the surface area of hyperboloids.",
      "Pi is used in the calculation of the volume of pyramids.",
      "Pi is used in the calculation of the surface area of pyramids.",
      "Pi is used in the calculation of the volume of prisms.",
      "Pi is used in the calculation of the surface area of prisms.",
      "Pi is used in the calculation of the volume of polyhedra.",
      "Pi is used in the calculation of the surface area of polyhedra.",
      "Pi is used in the calculation of the volume of irregular shapes.",
      "Pi is used in the calculation of the surface area of irregular shapes.",
      "Pi is used in the calculation of the volume of solids of revolution.",
      "Pi is used in the calculation of the surface area of solids of revolution.",
      "Pi is used in the calculation of the volume of irregular solids.",
      "Pi is used in the calculation of the surface area of irregular solids.",
      "Pi is used in the calculation of the volume of irregular polyhedra.",
      "Pi is used in the calculation of the surface area of irregular polyhedra.",
      "Pi is used in the calculation of the volume of irregular prisms.",
      "Pi is used in the calculation of the surface area of irregular prisms.",
      "Pi is used in the calculation of the volume of irregular pyramids.",
      "Pi is used in the calculation of the surface area of irregular pyramids.",
      "Pi is used in the calculation of the volume of irregular cones.",
      "Pi is used in the calculation of the surface area of irregular cones.",
      "Pi is used in the calculation of the volume of irregular cylinders.",
      "Pi is used in the calculation of the surface area of irregular cylinders.",
      "Pi is used in the calculation of the volume of irregular spheres.",
      "Pi is used in the calculation of the surface area of irregular spheres.",
      "Pi is used in the calculation of the volume of irregular ellipsoids.",
      "Pi is used in the calculation of the surface area of irregular ellipsoids.",
      "Pi is used in the calculation of the volume of irregular tori.",
      "Pi is used in the calculation of the surface area of irregular tori.",
      "Pi is used in the calculation of the volume of irregular paraboloids.",
      "Pi is used in the calculation of the surface area of irregular paraboloids.",
      "Pi is used in the calculation of the volume of irregular hyperboloids.",
      "Pi is used in the calculation of the surface area of irregular hyperboloids.",
      "Pi is used in the calculation of the volume of irregular solids of revolution.",
      "Pi is used in the calculation of the surface area of irregular solids of revolution.",
      "Pi is used in the calculation of the volume of irregular irregular shapes.",
      "Pi is used in the calculation of the surface area of irregular irregular shapes.",
      "Pi is used in the calculation of the volume of irregular irregular solids.",
      "Pi is used in the calculation of the surface area of irregular irregular solids.",
      "Pi is used in the calculation of the volume of irregular irregular polyhedra.",
      "Pi is used in the calculation of the surface area of irregular irregular polyhedra.",
      "Pi is used in the calculation of the volume of irregular irregular prisms.",
      "Pi is used in the calculation of the surface area of irregular irregular prisms.",
      "Pi is used in the calculation of the volume of irregular irregular pyramids.",
      "Pi is used in the calculation of the surface area of irregular irregular pyramids.",
      "Pi is used in the calculation of the volume of irregular irregular cones.",
      "Pi is used in the calculation of the surface area of irregular irregular cones.",
      "Pi is used in the calculation of the volume of irregular irregular cylinders.",
      "Pi is used in the calculation of the surface area of irregular irregular cylinders.",
      "Pi is used in the calculation of the volume of irregular irregular spheres.",
      "Pi is used in the calculation of the surface area of irregular irregular spheres.",
      "Pi is used in the calculation of the volume of irregular irregular ellipsoids.",
      "Pi is used in the calculation of the surface area of irregular irregular ellipsoids.",
      "Pi is used in the calculation of the volume of irregular irregular tori.",
      "Pi is used in the calculation of the surface area of irregular irregular tori.",
      "Pi is used in the calculation of the volume of irregular irregular paraboloids.",
      "Pi is used in the calculation of the surface area of irregular irregular paraboloids.",
      "Pi is used in the calculation of the volume of irregular irregular hyperboloids.",
      "Pi is used in the calculation of the surface area of irregular irregular hyperboloids.",
      "Pi is used in the calculation of the volume of irregular irregular solids of revolution.",
      "Pi is used in the calculation of the surface area of irregular irregular solids of revolution.",
      "Pi is used in the calculation of the volume of irregular irregular irregular shapes.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular shapes.",
      "Pi is used in the calculation of the volume of irregular irregular irregular solids.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular solids.",
      "Pi is used in the calculation of the volume of irregular irregular irregular polyhedra.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular polyhedra.",
      "Pi is used in the calculation of the volume of irregular irregular irregular prisms.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular prisms.",
      "Pi is used in the calculation of the volume of irregular irregular irregular pyramids.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular pyramids.",
      "Pi is used in the calculation of the volume of irregular irregular irregular cones.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular cones.",
      "Pi is used in the calculation of the volume of irregular irregular irregular cylinders.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular cylinders.",
      "Pi is used in the calculation of the volume of irregular irregular irregular spheres.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular spheres.",
      "Pi is used in the calculation of the volume of irregular irregular irregular ellipsoids.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular ellipsoids.",
      "Pi is used in the calculation of the volume of irregular irregular irregular tori.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular tori.",
      "Pi is used in the calculation of the volume of irregular irregular irregular paraboloids.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular paraboloids.",
      "Pi is used in the calculation of the volume of irregular irregular irregular hyperboloids.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular hyperboloids.",
      "Pi is used in the calculation of the volume of irregular irregular irregular solids of revolution.",
      "Pi is used in the calculation of the surface area of irregular irregular irregular solids of revolution.",
    ];
    
    // Randomly select a fact
    const randomFact = piFacts[Math.floor(Math.random() * piFacts.length)];
    
    return { fact: randomFact };
  },
});

export const tools = {
  FactTool: FactTool,
};